# Use root/example as user/password credentials
#
version: '3.1'

services:

  mysqlDb:
    # https://hub.docker.com/_/mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=myDb
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306

  postgresDb:
    # https://hub.docker.com/_/postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=myDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 3100:8080